blank_issues_enabled: false
contact_links:
- name: '📚 APIM Issue'
  about: If Something is missing in the API Manager product.
  url: https://github.com/wso2/product-apim/issues/new/choose
- name: '💬 Slack Channel'
  url: 'https://apim-slack.wso2.com/'
  about: |
    Chat with the community to get quick clarifications for your questions.
